version: "2"
services:
    server:
        build: ./server/
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./server:/server
            - /server/node_modules
    client:
        build: ./client/
        restart: always
        ports:
            - "3001:3001"
        depends_on:
            - 'server'
        volumes:
            - ./client:/client
            - /client/node_modules
        entrypoint: ["npm", "run", "start"]
